/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostCategory = IDL.Variant({
  'advertising' : IDL.Null,
  'announcement' : IDL.Null,
  'promotion' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const DashboardCounts = IDL.Record({
  'contactMessages' : IDL.Nat,
  'pendingAppointments' : IDL.Nat,
  'posts' : IDL.Nat,
  'totalAppointments' : IDL.Nat,
  'services' : IDL.Nat,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : IDL.Int,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : PostCategory,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const VisaCountry = IDL.Variant({
  'usa' : IDL.Null,
  'china' : IDL.Null,
  'france' : IDL.Null,
});
export const VisaDetails = IDL.Record({
  'title' : IDL.Text,
  'country' : VisaCountry,
  'fees' : IDL.Text,
  'description' : IDL.Text,
  'processingInfo' : IDL.Text,
  'requirements' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'preferredDate' : IDL.Text,
  'notes' : IDL.Text,
  'preferredTime' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), PostCategory, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'deleteBooking' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteContactMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteService' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardCounts' : IDL.Func([], [DashboardCounts], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
  'getVisa' : IDL.Func([VisaCountry], [IDL.Opt(VisaDetails)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'listPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'listVisas' : IDL.Func([], [IDL.Vec(VisaDetails)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [IDL.Bool], []),
  'updatePost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), PostCategory, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updateService' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updateVisa' : IDL.Func(
      [VisaCountry, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostCategory = IDL.Variant({
    'advertising' : IDL.Null,
    'announcement' : IDL.Null,
    'promotion' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const DashboardCounts = IDL.Record({
    'contactMessages' : IDL.Nat,
    'pendingAppointments' : IDL.Nat,
    'posts' : IDL.Nat,
    'totalAppointments' : IDL.Nat,
    'services' : IDL.Nat,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : IDL.Int,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : PostCategory,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const VisaCountry = IDL.Variant({
    'usa' : IDL.Null,
    'china' : IDL.Null,
    'france' : IDL.Null,
  });
  const VisaDetails = IDL.Record({
    'title' : IDL.Text,
    'country' : VisaCountry,
    'fees' : IDL.Text,
    'description' : IDL.Text,
    'processingInfo' : IDL.Text,
    'requirements' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'preferredDate' : IDL.Text,
    'notes' : IDL.Text,
    'preferredTime' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), PostCategory, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'createService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'deleteBooking' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteContactMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteService' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardCounts' : IDL.Func([], [DashboardCounts], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
    'getVisa' : IDL.Func([VisaCountry], [IDL.Opt(VisaDetails)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'listPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'listVisas' : IDL.Func([], [IDL.Vec(VisaDetails)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [IDL.Bool], []),
    'updatePost' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          PostCategory,
          IDL.Bool,
        ],
        [IDL.Bool],
        [],
      ),
    'updateService' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateVisa' : IDL.Func(
        [VisaCountry, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };