/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'serviceType' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'preferredDate' : string,
  'notes' : string,
  'preferredTime' : string,
  'phone' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface DashboardCounts {
  'contactMessages' : bigint,
  'pendingAppointments' : bigint,
  'posts' : bigint,
  'totalAppointments' : bigint,
  'services' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Post {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'published' : boolean,
  'createdAt' : bigint,
  'imageUrl' : [] | [string],
  'category' : PostCategory,
}
export type PostCategory = { 'advertising' : null } |
  { 'announcement' : null } |
  { 'promotion' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface Service {
  'id' : bigint,
  'title' : string,
  'active' : boolean,
  'createdAt' : bigint,
  'description' : string,
  'imageUrl' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export type VisaCountry = { 'usa' : null } |
  { 'china' : null } |
  { 'france' : null };
export interface VisaDetails {
  'title' : string,
  'country' : VisaCountry,
  'fees' : string,
  'description' : string,
  'processingInfo' : string,
  'requirements' : string,
}
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<
    [string, string, string, string, string, string, string],
    bigint
  >,
  'createPost' : ActorMethod<
    [string, string, [] | [string], PostCategory, boolean],
    bigint
  >,
  'createService' : ActorMethod<
    [string, string, [] | [string], boolean],
    bigint
  >,
  'deleteBooking' : ActorMethod<[bigint], boolean>,
  'deleteContactMessage' : ActorMethod<[bigint], boolean>,
  'deletePost' : ActorMethod<[bigint], boolean>,
  'deleteService' : ActorMethod<[bigint], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardCounts' : ActorMethod<[], DashboardCounts>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getService' : ActorMethod<[bigint], [] | [Service]>,
  'getVisa' : ActorMethod<[VisaCountry], [] | [VisaDetails]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listBookings' : ActorMethod<[], Array<Booking>>,
  'listContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'listPosts' : ActorMethod<[], Array<Post>>,
  'listServices' : ActorMethod<[], Array<Service>>,
  'listVisas' : ActorMethod<[], Array<VisaDetails>>,
  'schema' : ActorMethod<[], string>,
  'submitContactMessage' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], boolean>,
  'updatePost' : ActorMethod<
    [bigint, string, string, [] | [string], PostCategory, boolean],
    boolean
  >,
  'updateService' : ActorMethod<
    [bigint, string, string, [] | [string], boolean],
    boolean
  >,
  'updateVisa' : ActorMethod<
    [VisaCountry, string, string, string, string, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];